### ISSUE TITLE
这个zezha的代码大家都调通了没

### ISSUE THREAD

**Issue by TuringEmmy** [huawei-noah/Pretrained-Language-Model#113]
调的时候，错误太多了，读取数据集也是老错误，使用的是multinli数据没怎么代码里面有dev.tsv样式的代码，好难复现啊，bert复现10分钟，zezha复现一整天，哈哈哈，有哪位大佬有做过这块博客呀，复现完成那种，哈哈哈

**Comment by TuringEmmy** [comment]
run_classifier.py文件里面，对于验证集部分使用了dev.tsv,这个数据集在哪里呀，找不到呢

**Comment by jacobrxz** [comment]
数据集部分删掉了，可以用公开的下游任务数据集，预训练模型，下游代码都是开源的。
