### ISSUE TITLE
TinyBert distillation on downstream task : Why 2 steps ?

### ISSUE THREAD

**Issue by Colanim** [huawei-noah/Pretrained-Language-Model#13]
From the [paper ](https://arxiv.org/pdf/1909.10351.pdf):

> In our experiments, we firstly perform intermediate layer distillation (M ≥ m ≥ 0), then perform
the prediction-layer distillation (m = M + 1).

---

**Why is it necessary to perform the downstream task distillation in 2 separate steps ?**

Is it possible to distill on downstream task in one single step, using both loss at the same time ?  
Or maybe doing this is more difficult for the model to converge ?

**Comment by nlpBeginner** [comment]
> From the [paper ](https://arxiv.org/pdf/1909.10351.pdf):
> 
> > In our experiments, we firstly perform intermediate layer distillation (M ≥ m ≥ 0), then perform
> > the prediction-layer distillation (m = M + 1).
> 
> **Why is it necessary to perform the downstream task distillation in 2 separate steps ?**
> 
> Is it possible to distill on downstream task in one single step, using both loss at the same time ?
> Or maybe doing this is more difficult for the model to converge ?

Thanks for the interesting question! We have compared the one-step joint training and our proposed two-step learning, the results show that two-step learning has better performances and also does not need to tune the weights between different losses.
