### ISSUE TITLE
Training AutoTinyBert from scratch

### ISSUE THREAD

**Issue by sirily** [huawei-noah/Pretrained-Language-Model#137]
Hi! Thank you for the great repo!
I've tried to train AutoTinyBert from scratch with my data and got stuck with this error
`ValueError: Expected input batch_size (512) to match target batch_size (1024).`
at 1015 line in [modeling_super_kd.py](https://github.com/huawei-noah/Pretrained-Language-Model/blob/master/AutoTinyBERT/transformer/modeling_super_kd.py#L1015)

I did a little digging in your code and I think I found an error:
you take
`sequence_output = all_encoder_layers[-1]`
in [SuperBertModel forward pass](https://github.com/huawei-noah/Pretrained-Language-Model/blob/master/AutoTinyBERT/transformer/modeling_super_kd.py#L902) and then again take
`sequence_output = encoder_layers[-1]`
in [SuperBertForPreTraining forward pass](https://github.com/huawei-noah/Pretrained-Language-Model/blob/master/AutoTinyBERT/transformer/modeling_super_kd.py#L1003), so prediction scores are obtained only for the last sequence in the batch, and not for the entire batch.
I've commented out [this line](https://github.com/huawei-noah/Pretrained-Language-Model/blob/master/AutoTinyBERT/transformer/modeling_super_kd.py#L1003) and got the training run properly. I can send a PR to fix this small bug if you don't mind.

**Comment by zwjyyc** [comment]
Thanks! The Pull request is welcome!
