### ISSUE TITLE
词典大小对不上

### ISSUE THREAD

**Issue by chuanhuayang** [huawei-noah/Pretrained-Language-Model#15]
Task-specific Distillation阶段，teacher是fine-tuned bert base，student是general_tinybert，两者都是由bert base而来，bert base词典大小是21128，但是为啥下载的general_tinybert词典是30522？两者怎么对齐？
在task-specific distill阶段，student词典较大，输入到teacher会造成index越界。

```
student_logits, student_atts, student_reps = student_model(input_ids, segment_ids, input_mask, is_student=True)
teacher_logits, teacher_atts, teacher_reps = teacher_model(input_ids, segment_ids, input_mask)
```

**Comment by itsucks** [comment]
你下载的bert base应该是中文模型吧，老师模型需要用英文的bert base uncased

**Comment by chuanhuayang** [comment]
> 你下载的bert base应该是中文模型吧，老师模型需要用英文的bert base uncased
是的，teacher 模型是中文模型，tinyBert还没有对应中文模型的预训练模型是吧？

**Comment by itsucks** [comment]
tinyBert中文模型近期内会发布
