### ISSUE TITLE
使用 pytorch版本的TernaryBERT代码训练后得到的量化模型的“权重大小和之前一致”，并没有压缩，有点疑惑？

### ISSUE THREAD

**Issue by qiuwenbogdut** [huawei-noah/Pretrained-Language-Model#154]
![image](https://user-images.githubusercontent.com/17745161/141220506-c1c89576-38a2-43b5-8040-5f25d8d5c4ed.png)
![image](https://user-images.githubusercontent.com/17745161/141220728-6716c3f4-3306-4a92-9440-031fdb1267d9.png)
![image](https://user-images.githubusercontent.com/17745161/141220832-2ebff67c-21be-4b5a-9057-369ea6cf7bf8.png)

**Comment by itsucks** [comment]
你好，我们这里训练是一个伪量化的训练过程，在前馈过程中，加入量化操作，保证网络的计算在2/8bit下；由于框架训练的需要，真实的模型还是保留全精度的浮点型参数。至于要看到模型实际压缩的效果，比如8bit量化模型大小减小到1/4，则涉及到工程方面的工作，我们公开的代码里没有这方面的实现

**Comment by qiuwenbogdut** [comment]
非常感谢你的回复，thanks
