### ISSUE TITLE
Some errors in "run_classifier_ner.py" ? 

### ISSUE THREAD

**Issue by haiwentom** [huawei-noah/Pretrained-Language-Model#18]
脚本run_classifier_ner.py 中从第1105行到第1115行的缩进有问题吧？这块代码应该包含在第1076行的else循环中？
`    result = estimator.evaluate(input_fn=predict_input_fn, checkpoint_path=FLAGS.init_checkpoint)  # predict
    output_predict_file = os.path.join(FLAGS.output_dir, "test_results.tsv")
    eval_re_path = os.path.join(FLAGS.output_dir, "eval")
    if not os.path.exists(eval_re_path):
        os.mkdir(eval_re_path)
    output_test_file = os.path.join(eval_re_path, "test_results.txt")
    with tf.gfile.GFile(output_test_file, "w") as writer:
        tf.logging.info("***** Test results *****")
        for key in sorted(result.keys()):
            tf.logging.info("  %s = %s", key, str(result[key]))
            writer.write("%s = %s\n" % (key, str(result[key])))`

**Comment by dsl-light** [comment]
确实是有问题，新版代码bug已经被修复了
