### ISSUE TITLE
AutoTinyBERT models not accessible

### ISSUE THREAD

**Issue by AdityaKane2001** [huawei-noah/Pretrained-Language-Model#185]
Thanks for the awesome work on [AutoTinyBERT](https://aclanthology.org/2021.acl-long.400.pdf)! 

We would like to use your final model checkpoints. However, the links provided in  the [AutoTinyBERT Model Zoo](https://github.com/huawei-noah/Pretrained-Language-Model/tree/master/AutoTinyBERT#model-zoo) are not accessible. It would be of great help to our work if you could share the model checkpoints. 

Looking forward to your response.

**Comment by fraboeni** [comment]
Thank you very much for this great repo. Also [General_TinyBERT(4layer-312dim)] and general models do not seem to be available anymore.

Is there any chance that you could share them again?

**Comment by zwjyyc** [comment]
Please access these models at https://huggingface.co/huawei-noah.
