### ISSUE TITLE
Wukong 论文table9问题

### ISSUE THREAD

**Issue by bixiaopeng0** [huawei-noah/Pretrained-Language-Model#194]
请问论文中Table 9中的CLI P和FLIP是重新训练的吗？测试集都是中文，官方release的模型是在英文数据集训练的，好像没法直接测呢。

**Comment by zihoudanyuan** [comment]
看论文5.1写的“We have three variations of pretraining Chinese models: global
similarity (CLIP-style); token-wise similarity (FILIP-style) and token-wise similarity with token
reduction layer (Wukong-style).”应该是重新训练了CLIP和FILIP权重吧

**Comment by mengxj08** [comment]
@bixiaopeng0 对的，中文模型都是我们自己训练的，模型文件可以在[悟空主页](https://wukong-dataset.github.io/wukong-dataset/benchmark.html)下载。
