### ISSUE TITLE
请问有尝试过在sequence labelling任务上验证过能力么？

### ISSUE THREAD

**Issue by 1024er** [huawei-noah/Pretrained-Language-Model#2]

**Comment by itsucks** [comment]
你指的是Nezha模型还是TinyBERT呢？

**Comment by 1024er** [comment]
> 你指的是Nezha模型还是TinyBERT呢？

TinyBERT

**Comment by itsucks** [comment]
> > 你指的是Nezha模型还是TinyBERT呢？
> 
> TinyBERT

我们在做论文中提及的glue任务的同时，另外在意图分类、槽位提取联合训练的任务上做了相关验证，也是有效的，意图分类任务相对简单，指标逼近bert base，槽位提取有少于一个点的损失

**Comment by 1024er** [comment]
再请教一下，我看论文里写了 Embedding-layer Distillation.，但是我再 general_distill.py 文件中没看到这部分的 loss 啊？

**Comment by 1024er** [comment]
这个代码里面没有Squad的部分吧？

**Comment by nlpBeginner** [comment]
> 这个代码里面没有Squad的部分吧？

是的，我们目前正在整理相关代码，会尽快更新的。

**Comment by Single430** [comment]
@nlpBeginner  您好，请问2020了，还需要多久才能发布上面说的相关代码

**Comment by zshy1205** [comment]
> @nlpBeginner 您好，请问2020了，还需要多久才能发布上面说的相关代码

应该是没了~中文版的tinybert也没放出来。

**Comment by chenjxthu** [comment]
是不是效果不行？
