### ISSUE TITLE
希望提供一些体量更小的NEZHA预训练模型

### ISSUE THREAD

**Issue by haiwentom** [huawei-noah/Pretrained-Language-Model#20]
有时候比较关注inference速度。比如类似于 albert_tiny_zh,albert_small_zh的模型，
给个 nezha_tiny_zh,nezha_small_zh之类的小模型以提升inference速度，哈哈哈哈哈哈
![c2cf01c6-873c-11e5-8216-a00474c8e717](https://user-images.githubusercontent.com/13297399/70777203-1dd76780-1dba-11ea-8c9c-ae1e0bbbad6a.jpg)

**Comment by zhuhaijun-ai** [comment]
不清楚是否公布，目前已经用tiny-nezha刷了clue
![image](https://user-images.githubusercontent.com/53253727/80085710-32f3ac80-858b-11ea-9a27-da4f183bdec1.png)

**Comment by jacobrxz** [comment]
您好，如果有相关开源计划我们会第一时间告知，多谢关注~
