### ISSUE TITLE
TinyBERT有中文版吗

### ISSUE THREAD

**Issue by MrRace** [huawei-noah/Pretrained-Language-Model#21]
如题，请问下TinyBERT发布中文预训练版吗？谢谢！

**Comment by nlpBeginner** [comment]
> 如题，请问下TinyBERT发布中文预训练版吗？谢谢！

目前，TinyBERT的中文版在训练和测试中，后续会发布的~

**Comment by Cumberbatch08** [comment]
@nlpBeginner  您好，通用中文版tinybert发布了吗？

**Comment by oldstree** [comment]
@nlpBeginner 您好，中文的tinyBert发布了吗？

**Comment by SunShuoying** [comment]
@nlpBeginner 您好，看到tinybert开源很激动，特别希望能用到中文场景，请问啥时候能发布中文的tinyBert呢？

**Comment by jacobrxz** [comment]
您好，如果有相关开源计划我们会第一时间告知，多谢关注~

**Comment by Jeff654** [comment]
> > 如题，请问下TinyBERT发布中文预训练版吗？谢谢！
> 
> 目前，TinyBERT的中文版在训练和测试中，后续会发布的~

您好，目前好像还没在找到相关的中文 TinyBERT 模型，请问还会发布吗

**Comment by Jeff654** [comment]
> @nlpBeginner 您好，看到tinybert开源很激动，特别希望能用到中文场景，请问啥时候能发布中文的tinyBert呢？

您好，目前好像还没有找到关于中文 TinyBERT 模型，请问您有自己去 train 吗？

**Comment by SYX107** [comment]
> > 如题，请问下TinyBERT发布中文预训练版吗？谢谢！
> 
> 目前，TinyBERT的中文版在训练和测试中，后续会发布的~

你好 请问还会发布吗？
