### ISSUE TITLE
tinybert预训练蒸馏两个问题

### ISSUE THREAD

**Issue by qgzang** [huawei-noah/Pretrained-Language-Model#24]
1. 预训练蒸馏只有attention和encoder_layer loss, 好像没有mask lm的loss？
2. 如果没有mask lm的loss, 怎么直接测试蒸馏好的小模型效果？

**Comment by nlpBeginner** [comment]
@qgzang 1. 在General Distillation 中没有做mask lm 的loss。

**Comment by qgzang** [comment]
> @qgzang
> 
> 1. 在General Distillation 中没有做mask lm 的loss。
> 2. 对于General Distillation我们一般训练2轮，然后在特定任务上fine-tuning。结果表明即使没有mlm loss，general distillation也能得到比较好的效果。
> 3. TinyBERT的工作，还包含data augmentation  and Task-specific Distillation，在这一步之后，其效果会非常接近bert-base的效果，甚至在有些任务上会优于bert-base。

感谢你的回复，我目前在general distillation这一步，将student网络的mlm输出层权重固定成和teacher网络一样，不更新。我理解如果蒸馏的student网络足够好，最后一个encoder layer的输出应该会比较接近teacher网络的输出，所以student网络的mlm loss应该会比较接近teacher网络mlm loss，但是我的试验现象是student网络的mlm loss会比teacher网络差40%，所以比较疑惑。另外，可以提供att-loss 和rep_loss在2轮后的大致指标吗？再次表示感谢。

**Comment by nlpBeginner** [comment]
@qgzang 
因为我们设定不太一样，所以不能判断你的mlm loss 是否正常，你可以简单在若干任务上fine-tune试下general tinybert的效果。att-loss和rep-loss 2 轮之后下降分别为 28.8->7.7和2.0->1.1左右。

**Comment by qgzang** [comment]
> @qgzang
> 因为我们设定不太一样，所以不能判断你的mlm loss 是否正常，你可以简单在若干任务上fine-tune试下general tinybert的效果。att-loss和rep-loss 2 轮之后下降分别为 28.8->7.7和2.0->1.1左右。

好的，谢谢，我再尝试下。

**Comment by Asleda** [comment]
@nlpBeginner 你好 ，我训练了3轮，目前att-loss->13.7235 rep-loss->3.6131
您说的“att-loss和rep-loss 2 轮之后下降分别为 28.8->7.7和2.0->1.1左右”，是不是我们的参数不一致
使用student model的参数如下：
{
  "attention_probs_dropout_prob": 0.1,
  "cell": {},
  "emb_size": 312,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 312,
  "initializer_range": 0.02,
  "intermediate_size": 1200,
  "max_position_embeddings": 512,
  "num_attention_heads": 12,
  "num_hidden_layers": 4,
  "pre_trained": "",
  "structure": [],
  "type_vocab_size": 2,
  "vocab_size": 21128
}

**Comment by nlpBeginner** [comment]
student model的参数是一样的，就是我们在训练的是长度是128的模型

**Comment by Cumberbatch08** [comment]
@Asleda  您好，中文版的通用蒸馏模型您训练出来了吗？

**Comment by MrRace** [comment]
@Asleda 您中文wiki原始语料是？ 转换到TinyBERT所用的格式，脚本能否提供下。谢谢！

**Comment by oldstree** [comment]
@Asleda 我也是在中文的wiki上训练模型，att-loss->5.  rep-loss->1.   担心模型的训练的有问题。

**Comment by ann22** [comment]
> @nlpBeginner 你好 ，我训练了3轮，仅使用中文wiki语料 目前att-loss->13.7235 rep-loss->3.6131
> 您说的“att-loss和rep-loss 2 轮之后下降分别为 28.8->7.7和2.0->1.1左右”，是不是我们的参数不一致
> 使用student model的参数如下：
> {
> "attention_probs_dropout_prob": 0.1,
> "cell": {},
> "emb_size": 312,
> "hidden_act": "gelu",
> "hidden_dropout_prob": 0.1,
> "hidden_size": 312,
> "initializer_range": 0.02,
> "intermediate_size": 1200,
> "max_position_embeddings": 512,
> "num_attention_heads": 12,
> "num_hidden_layers": 4,
> "pre_trained": "",
> "structure": [],
> "type_vocab_size": 2,
> "vocab_size": 21128
> }

您好，请问一下中文预训练蒸馏模型第一步生成json形式语料中train_corpus是zhwiki吗
