### ISSUE TITLE
请问会不会出现过拟合的情况，BERT-PKD专门解决了过拟合的情况

### ISSUE THREAD

**Issue by gongel** [huawei-noah/Pretrained-Language-Model#25]
[Patient Knowledge Distillation for BERT Model Compression](https://www.aclweb.org/anthology/D19-1441.pdf)

**Comment by nlpBeginner** [comment]
@gongel 你所说的过拟合，具体指什么情况。

**Comment by gongel** [comment]
已经理解了，不好意思。
