### ISSUE TITLE
Data Augmentation

### ISSUE THREAD

**Issue by gongel** [huawei-noah/Pretrained-Language-Model#28]
In the phase of [Data Augmentation](https://github.com/huawei-noah/Pretrained-Language-Model/tree/master/TinyBERT#data-augmentation), pretrained_bert_model is General_TinyBERT in data_augmentation.py but is "pre-trained language model BERT" in the description.

**Comment by nlpBeginner** [comment]
@gongel in file data_augmentation.py, the paramerter "pretrained_bert_model" represents the pre-trained language model BERT as we described in  [Data Augmentation](https://github.com/huawei-noah/Pretrained-Language-Model/tree/master/TinyBERT#data-augmentation)

**Comment by gongel** [comment]
in [this line](https://github.com/huawei-noah/Pretrained-Language-Model/blob/05462fed9247cc0fc12e741f05e574caa25a3e87/TinyBERT/data_augmentation.py#L289) in data_augmentation.py, it will call  [the line](https://github.com/huawei-noah/Pretrained-Language-Model/blob/05462fed9247cc0fc12e741f05e574caa25a3e87/TinyBERT/transformer/modeling.py#L686), but CONFIG_NAME is  "config.json" not BERT_CONFIG_NAME(= 'bert_config.json').

**Comment by nlpBeginner** [comment]
@gongel  It doesn't matter, in the "pretrained_bert_model", the name of config file is "config.json" and the name of parameters file is "pytorch_model.bin" , the vocab file is "vocab.txt", you can change it.

**Comment by gongel** [comment]
@nlpBeginner Thank for your answer. I got it now and I downloaded tf-version pretrained bert model before😓.
