### ISSUE TITLE
Task-specific Distillation

### ISSUE THREAD

**Issue by gongel** [huawei-noah/Pretrained-Language-Model#29]
In [Task-specific Distillation](https://github.com/huawei-noah/Pretrained-Language-Model/tree/master/TinyBERT#task-specific-distillation), the description says "${FT_BERT_BASE_DIR}$ contains the fine-tuned BERT-base model", could you offer me the fine-tuned BERT-base model to reproduce results in the paper?

**Comment by nlpBeginner** [comment]
@gongel  Thanks! You can easily get the fine-tuned BERT-based model by following the original setting in BERT paper.  We think that fine-tuning bert model is not a difficult step in reproducing our results.

**Comment by gongel** [comment]
@gongel Thank for your reply.
