### ISSUE TITLE
How long does it approx. take to pre-train tinybert?

### ISSUE THREAD

**Issue by volker42maru** [huawei-noah/Pretrained-Language-Model#3]
I couldn't find the infomation in the paper. Thanks :)

**Comment by cht-github** [comment]
> I couldn't find the infomation in the paper. Thanks :)

Thanks for your interest in TinyBERT. Pre-training tinyBERT tasks 2 days under the settings: max_seq=128, batch_size=256, 8V100 and Wiki corpus.

**Comment by volker42maru** [comment]
Thanks for the info. I was wondering, if you also plan to release the task-distilled models for squad1/2? Or the code to do task-distillation on squad?

**Comment by cht-github** [comment]
> Thanks for the info. I was wondering, if you also plan to release the task-distilled models for squad1/2? Or the code to do task-distillation on squad?

Sure! We will public the SQuAD-releated models after the release of chinese TinyBERT.  Too many things to do.
