### ISSUE TITLE
Task specific第二阶段（prediction layer training）的训练需要使用数据增强后的数据集嘛？

### ISSUE THREAD

**Issue by yxjhuster** [huawei-noah/Pretrained-Language-Model#34]
用论文中的数据增强的方法处理中文语料似乎会带来很严重的歧义， 这在intermediate layer training的部分影响不是很大， 但是在下游任务时影响巨大。似乎使用未增强的数据集会更合适？

**Comment by nlpBeginner** [comment]
@yxjhuster 
对于一些简单的任务，不使用数据增强也能近似达到bert-base的结果，对于一些复杂的任务，使用数据增强可以提升性能。经过实验验证，数据增强对中文的任务也是有提升的。

**Comment by yxjhuster** [comment]
> @yxjhuster
> 对于一些简单的任务，不使用数据增强也能近似达到bert-base的结果，对于一些复杂的任务，使用数据增强可以提升性能。经过实验验证，数据增强对中文的任务也是有提升的。

好的，谢谢。还有一个小问题，就是我发现在代码里面，您设了一些英文的stop words（诸如情态动词，人称代词之类的）不参与替换， 请问中文的数据增强中，您有没有用过类似的小trick

**Comment by nlpBeginner** [comment]
@yxjhuster 
我没有尝试过这样的trick，不过您可以尝试一下，效果应该会有所提升。

**Comment by Tian14267** [comment]
请问一下，python pregenerate_training_data.py --train_corpus ${CORPUS_RAW} \
--bert_model ${BERT_BASE_DIR}$
--reduce_memory --do_lower_case
--epochs_to_generate 3
--output_dir ${CORPUS_JSON_DIR}$
这里面的 --train_corpus ${CORPUS_RAW} 、bert_model ${BERT_BASE_DIR}$、--output_dir ${CORPUS_JSON_DIR}$ 所对应的文件分别在哪啊？我没法直接运行这个代码 @jacobrxz @nlpBeginner @yxjhuster
