### ISSUE TITLE
General_TinyBERT 模型可以提供 tensorflow版本吗？

### ISSUE THREAD

**Issue by sanshanxiashi** [huawei-noah/Pretrained-Language-Model#35]
我看模型文件都是 pytorch的，就想问问能不能把tensorflow版本的也帮忙训一下，谢谢！

**Comment by itsucks** [comment]
你可以试试直接把pytorch模型转成tf的，huggingface提供了转换的脚本，不过要稍作修改https://github.com/huggingface/transformers/blob/master/src/transformers/convert_bert_pytorch_checkpoint_to_original_tf.py

**Comment by XingWu01** [comment]
> 我看模型文件都是 pytorch的，就想问问能不能把tensorflow版本的也帮忙训一下，谢谢！

您好，请问您转成功了么？

**Comment by 1024er** [comment]
> > 我看模型文件都是 pytorch的，就想问问能不能把tensorflow版本的也帮忙训一下，谢谢！
> 
> 您好，请问您转成功了么？
这里有转好的 PaddlePaddle 版本和 Tensorflow 版本的
https://pan.baidu.com/s/4pOxsco7

**Comment by sanshanxiashi** [comment]
@1024er @itsucks 多谢了！

**Comment by asilentwolf** [comment]
> @1024er @itsucks 多谢了！
tensorflow版本的链接失效了， 能再发一下吗？

**Comment by asilentwolf** [comment]
> > > 我看模型文件都是 pytorch的，就想问问能不能把tensorflow版本的也帮忙训一下，谢谢！
> > 
> > 
> > 您好，请问您转成功了么？
> > 这里有转好的 PaddlePaddle 版本和 Tensorflow 版本的
> > https://pan.baidu.com/s/4pOxsco7

tensorflow版本的链接失效了，能再发一个嘛？

**Comment by guotong1988** [comment]
Same question.

**Comment by guotong1988** [comment]
请问下有了tensorflow的模型，怎么弄到tensorflow代码里？

**Comment by sesameintro** [comment]
> > > 我看模型文件都是 pytorch的，就想问问能不能把tensorflow版本的也帮忙训一下，谢谢！
> > 
> > 
> > 您好，请问您转成功了么？
> > 这里有转好的 PaddlePaddle 版本和 Tensorflow 版本的
> > https://pan.baidu.com/s/4pOxsco7

你好~ 我也想求一个新链接~ 谢谢

**Comment by ThreeBucks** [comment]
here is the solution: https://www.jianshu.com/p/28f2cf186dae
