### ISSUE TITLE
Task-specific Distillation 的step1中load_tf_weights_in_bert出现下面的问题

### ISSUE THREAD

**Issue by wanghia** [huawei-noah/Pretrained-Language-Model#36]
Initialize PyTorch weight ['bert', 'encoder', 'layer_9', 'attention', 'self', 'key', 'bias']
Initialize PyTorch weight ['bert', 'encoder', 'layer_9', 'attention', 'self', 'key', 'kernel']
Initialize PyTorch weight ['bert', 'encoder', 'layer_9', 'attention', 'self', 'query', 'bias']
Initialize PyTorch weight ['bert', 'encoder', 'layer_9', 'attention', 'self', 'query', 'kernel']
Initialize PyTorch weight ['bert', 'encoder', 'layer_9', 'attention', 'self', 'value', 'bias']
Initialize PyTorch weight ['bert', 'encoder', 'layer_9', 'attention', 'self', 'value', 'kernel']
Initialize PyTorch weight ['bert', 'encoder', 'layer_9', 'intermediate', 'dense', 'bias']
Initialize PyTorch weight ['bert', 'encoder', 'layer_9', 'intermediate', 'dense', 'kernel']
Initialize PyTorch weight ['bert', 'encoder', 'layer_9', 'output', 'LayerNorm', 'beta']
Initialize PyTorch weight ['bert', 'encoder', 'layer_9', 'output', 'LayerNorm', 'gamma']
Initialize PyTorch weight ['bert', 'encoder', 'layer_9', 'output', 'dense', 'bias']
Initialize PyTorch weight ['bert', 'encoder', 'layer_9', 'output', 'dense', 'kernel']
Initialize PyTorch weight ['bert', 'pooler', 'dense', 'bias']
Initialize PyTorch weight ['bert', 'pooler', 'dense', 'kernel']
Skipping cls/predictions/output_bias
Skipping cls/predictions/output_bias
Skipping cls/predictions/output_bias
Traceback (most recent call last):
  File "task_distill.py", line 1162, in <module>
    main()
  File "task_distill.py", line 927, in main
    teacher_model = TinyBertForSequenceClassification.from_pretrained(args.teacher_model, num_labels=num_labels, from_tf=True)
  File "/mnt/disk0/home/xx/project/demo/tinybert/TinyBERT/transformer/modeling.py", line 706, in from_pretrained
    return load_tf_weights_in_bert(model, weights_path)
  File "/mnt/disk0/home/xx/project/demo/tinybert/TinyBERT/transformer/modeling.py", line 119, in load_tf_weights_in_bert
    assert pointer.shape == array.shape
  File "/home/xx/install/anaconda3/envs/torch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 576, in __getattr__
    type(self).__name__, name))
AttributeError: 'TinyBertForSequenceClassification' object has no attribute 'shape'

**Comment by wanghia** [comment]
Initialize PyTorch weight ['bert', 'encoder', 'layer_9', 'attention', 'self', 'key', 'bias']
Initialize PyTorch weight ['bert', 'encoder', 'layer_9', 'attention', 'self', 'key', 'kernel']
Initialize PyTorch weight ['bert', 'encoder', 'layer_9', 'attention', 'self', 'query', 'bias']
Initialize PyTorch weight ['bert', 'encoder', 'layer_9', 'attention', 'self', 'query', 'kernel']
Initialize PyTorch weight ['bert', 'encoder', 'layer_9', 'attention', 'self', 'value', 'bias']
Initialize PyTorch weight ['bert', 'encoder', 'layer_9', 'attention', 'self', 'value', 'kernel']
Initialize PyTorch weight ['bert', 'encoder', 'layer_9', 'intermediate', 'dense', 'bias']
Initialize PyTorch weight ['bert', 'encoder', 'layer_9', 'intermediate', 'dense', 'kernel']
Initialize PyTorch weight ['bert', 'encoder', 'layer_9', 'output', 'LayerNorm', 'beta']
Initialize PyTorch weight ['bert', 'encoder', 'layer_9', 'output', 'LayerNorm', 'gamma']
Initialize PyTorch weight ['bert', 'encoder', 'layer_9', 'output', 'dense', 'bias']
Initialize PyTorch weight ['bert', 'encoder', 'layer_9', 'output', 'dense', 'kernel']
Initialize PyTorch weight ['bert', 'pooler', 'dense', 'bias']
Initialize PyTorch weight ['bert', 'pooler', 'dense', 'kernel']
Skipping cls/predictions/output_bias
Skipping cls/predictions/output_bias
Skipping cls/predictions/output_bias
Traceback (most recent call last):
  File "task_distill.py", line 1162, in <module>
    main()
  File "task_distill.py", line 927, in main
    teacher_model = TinyBertForSequenceClassification.from_pretrained(args.teacher_model, num_labels=num_labels, from_tf=True)
  File "/mnt/disk0/home/wanghai/project/demo/tinybert/TinyBERT/transformer/modeling.py", line 706, in from_pretrained
    return load_tf_weights_in_bert(model, weights_path)
  File "/mnt/disk0/home/wanghai/project/demo/tinybert/TinyBERT/transformer/modeling.py", line 119, in load_tf_weights_in_bert
    assert pointer.shape == array.shape
  File "/home/wanghai/install/anaconda3/envs/torch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 576, in __getattr__
    type(self).__name__, name))
AttributeError: 'TinyBertForSequenceClassification' object has no attribute 'shape'

**Comment by wanghia** [comment]
解决方案：
class TinyBertForSequenceClassification(BertPreTrainedModel):
    def __init__(self, config, num_labels, fit_size=768):
        super(TinyBertForSequenceClassification, self).__init__(config)
        self.num_labels = num_labels
        self.bert = BertModel(config)
        self.dropout = nn.Dropout(config.hidden_dropout_prob)
        self.classifier = nn.Linear(config.hidden_size, num_labels)
        self.fit_dense = nn.Linear(config.hidden_size, fit_size)
        ###answer from https://github.com/huggingface/transformers/issues/676
        self.weight = Variable(torch.ones(num_labels, config.hidden_size), requires_grad=True)
        self.bias = Variable(torch.ones(num_labels), requires_grad=True)
        self.apply(self.init_bert_weights)

**Comment by wanghia** [comment]
请问有人通过Task-specific Distillation复现SST2的结果吗?  求指导一下参数设置，以及流程，teacher model是bert fine-tuning好的checkpoint

**Comment by ThreeBucks** [comment]
here is the solution: https://www.jianshu.com/p/28f2cf186dae
