### ISSUE TITLE
Question towards TinyBERT Data Augmentation ${GLOVE_EMB}$

### ISSUE THREAD

**Issue by MichaelCaohn** [huawei-noah/Pretrained-Language-Model#37]
Hi, all

In the part of Data Augmentation I have seen “--glove_embs ${GLOVE_EMB}$”, I am wondering what should I use to replace this part: "${GLOVE_EMB}$"

I have noticed from the code in the data_augmentation.py, it mentioned it is the glove embedding file. If we should replace "${GLOVE_EMB}$" with the location of the glove embedding file. 

May I know where can we get the glove embedding file? Could you provide me with a link?

**Comment by nlpBeginner** [comment]
@astrongstorm  "${GLOVE_EMB}$" represents the location of the glove embedding file. you can download it in https://nlp.stanford.edu/projects/glove/.

**Comment by gongel** [comment]
@nlpBeginner And which dimension of glove embedding ?

**Comment by nlpBeginner** [comment]
![image](https://user-images.githubusercontent.com/34981073/73913138-38791900-48f1-11ea-964b-a8c0e7b616e2.png)
@gongel

**Comment by gongel** [comment]
> ![image](https://user-images.githubusercontent.com/34981073/73913138-38791900-48f1-11ea-964b-a8c0e7b616e2.png)
> @gongel

Thx.

**Comment by SunShuoying** [comment]
@nlpBeginner 你好，请问中文任务应该用什么？

**Comment by FFChyan** [comment]
> @nlpBeginner 你好，请问中文任务应该用什么？

Someone has given explanations in #83 that may help you.
https://github.com/huawei-noah/Pretrained-Language-Model/issues/83
