### ISSUE TITLE
Isn't TinyBert Equivalent to copying teacher Bert attention/hidden weights

### ISSUE THREAD

**Issue by osaleh** [huawei-noah/Pretrained-Language-Model#38]
Looking at Eq 7-9 in the paper (https://arxiv.org/pdf/1909.10351.pdf) and assuming that the student and teacher models have the same dimensionality (i.e. d=d') then how is TinyBert any different (better) than initializing a 4 layer Bert model with the hidden, embedding, and attention weights of the corresponding teacher model? Since you are doing a MSE() loss in eq 7-9 then the minimum of this loss is achieved (assuming d=d', M < N) when Ai_s = Ai_t, H_s=H_t, E_s=E_t => so whats the advantage of using TinyBert for general distillation (GD)  (where you dont do the prediction layer Hinton distillation) over simply cloning the selected teacher layers onto the student? Maybe you can clarify?

**Comment by nlpBeginner** [comment]
@osaleh 
you can refer to APPENDIX D: BERTsmall AS INITIALIZATION OF GENERAL TINYBERT  and https://openreview.net/forum?id=rJx0Q6EFPB&noteId=SJxEmUtYjr where we clarified.
