### ISSUE TITLE
Is there a plan to release tf-version tinyBert?

### ISSUE THREAD

**Issue by ghostyoona** [huawei-noah/Pretrained-Language-Model#4]
Hi! 
THX for the great work! I'm looking for a pretrained model like bert but with higher inference speed. So I wonder if the tinyBert-torch model can be uesd by NEZHA or is there a plan to release a tf version tinyBert?
Thank you.

**Comment by itsucks** [comment]
The tinyBert-torch models we released are standard bert-like structure, you can try the script provided by huggingface to convert the pytorch model to tf checkpoint for tf use. As for tf version tinyBert or tinyNezha, we're still working on it.

**Comment by ghostyoona** [comment]
@itsucks THX a lot!
