### ISSUE TITLE
Release other variants of general TinyBert

### ISSUE THREAD

**Issue by luyug** [huawei-noah/Pretrained-Language-Model#40]
Hi,

I found in the paper that you have experimented with four different variants of TinyBert (with different number of layers and dimension) , among which two have general distilled models released. Would it be possible to release general TinyBert for the other two variants(4layer-768dim and 6layer-312dim)?

Thanks

**Comment by nlpBeginner** [comment]
@luyug 
sorry, we have no plan to release the others.
