### ISSUE TITLE
中文版蒸馏模型

### ISSUE THREAD

**Issue by Cumberbatch08** [huawei-noah/Pretrained-Language-Model#41]
1. 官方最近有更新中文版模型计划吗？
2. 有人自己训练蒸馏中文版模型吗？蒸馏模型做下游任务效果如何？

**Comment by wykdg** [comment]
2.跟英文的差不多，效果缩水一点

**Comment by Cumberbatch08** [comment]
tinybert通用蒸馏模型可以发布出来吗？或者是共享一下？

**Comment by yxjhuster** [comment]
简单任务的话性能和论文里差不多，复杂任务有所缩水

**Comment by guotong1988** [comment]
同问。

**Comment by DeligientSloth** [comment]
> 1. 官方最近有更新中文版模型计划吗？
> 2. 有人自己训练蒸馏中文版模型吗？蒸馏模型做下游任务效果如何？

请问你搞来了中文蒸馏模型了吗？

**Comment by ann22** [comment]
> 2.跟英文的差不多，效果缩水一点

请问如何自己训练中文版蒸馏模型

**Comment by wykdg** [comment]
直接用textbrewer吧

**Comment by SunShuoying** [comment]
@wykdg 老哥，你是怎么做的能给个教程不？

**Comment by jacobrxz** [comment]
您好，如果有相关开源计划我们会第一时间告知，多谢关注~
