### ISSUE TITLE
Multi-languages support ?

### ISSUE THREAD

**Issue by AlafateABULIMITI** [huawei-noah/Pretrained-Language-Model#42]
I was wondering whether it is possible to use this model for other languages (e.g. French)?

I checked the vocab.txt, probably it is for English for now?

**Comment by AlafateABULIMITI** [comment]
I did not find the letters like è ê é ö à... who are in the French alphabet.

**Comment by ItachiUchihaVictor** [comment]
> I was wondering whether it is possible to use this model for other languages (e.g. French)?
> 
> I checked the vocab.txt, probably it is for English for now?

Our multilingual model is released now. Please visit https://github.com/huawei-noah/Pretrained-Language-Model/tree/master/NEZHA-TensorFlow.
