### ISSUE TITLE
No such file or directory: '/cache/shelf.db.dat'

### ISSUE THREAD

**Issue by bvnagaraju** [huawei-noah/Pretrained-Language-Model#46]
trying to run prepare script and getting this error.
how is this file created? or this part of setup

No such file or directory: '/cache/shelf.db.dat'

**Comment by bvnagaraju** [comment]
got it working

**Comment by bijibing** [comment]
@bvnagaraju I got the same problem. Could you share the solution ?

**Comment by vincentlux** [comment]
Try to remove `/cache` and change flag to 'c' works for me.
