### ISSUE TITLE
蒸馏的效果问题？

### ISSUE THREAD

**Issue by jianqianzhou** [huawei-noah/Pretrained-Language-Model#49]
原始的教师网络通过fine-tune后的准确率大概在93%，使用大量未打标签数据输入到教师网络获取打标签数据，将这些数据输入到四层的bert（作为学生网络）中训练，以下两种情况：
（1）未添加中间层loss（atten、embebeding、encoder等），仅仅采用学生的硬标签作为loss，准确率为89%；
（2）添加中间层loss蒸馏，准确率为90%。
这说明中间层loss对最终学生网络准确率影响比较小？不知道TinyBert有测试损失函数添加对蒸馏准确率影响有多大？是不是我这边蒸馏的有问题呢？

**Comment by PathricLee** [comment]
你的这里面(1)是指不适用蒸馏么，直接随机初始化的tinybert在label上finetune有89%？

**Comment by jianqianzhou** [comment]
> 你的这里面(1)是指不适用蒸馏么，直接随机初始化的tinybert在label上finetune有89%？

就是直接裁剪到4层，不添加教师的loss函数
