### ISSUE TITLE
Can you upload the model to other platforms?

### ISSUE THREAD

**Issue by qlwang25** [huawei-noah/Pretrained-Language-Model#5]
It takes a long time to download four  models. 
Can you upload the models to other platforms (e.g., google drive)?
![image](https://user-images.githubusercontent.com/38132016/70295408-e26cf400-1821-11ea-9526-8a6798269ad8.png)

Thanks !

**Comment by jacobrxz** [comment]
Most of the Chinese Language Model researchers are from China, so we choose BaiduYun, but we will consider your suggestion~ Thanks~

**Comment by qlwang25** [comment]
但是百度网盘的下载速度真的好慢啊（真怀疑它是不是限速了？:confused:）
![image](https://user-images.githubusercontent.com/38132016/70313703-10b5f800-1851-11ea-8fdb-f7f4bf90b2ea.png)

要是你们没有打算改变，那我还是慢慢下吧 
:smile:

**Comment by jacobrxz** [comment]
> 但是百度网盘的下载速度真的好慢啊（真怀疑它是不是限速了？😕）
> ![image](https://user-images.githubusercontent.com/38132016/70313703-10b5f800-1851-11ea-8fdb-f7f4bf90b2ea.png)
> 
> 要是你们没有打算改变，那我还是慢慢下吧
> 😄

百度网盘貌似是限速的，不过估计我们改完你已经下完了😄

**Comment by zhengwsh** [comment]
@jacobrxz  可以不同模型分开提供下载链接吗? (另外请问有无和RoBERTa-wwm-ext-large[8]比较的计划)

**Comment by jacobrxz** [comment]
> @jacobrxz 可以不同模型分开提供下载链接吗? (另外请问有无和RoBERTa-wwm-ext-large[8]比较的计划)

嗯 好的 我会反馈一下您的意见

**Comment by shenhuaze** [comment]
@jacobrxz  您好，TinyBERT只有google drive的下载链接，国内如果不翻墙的话，无法下载google drive上的模型，能否增加一个国内可以直接下载的链接，谢谢~

**Comment by hes666** [comment]
> @jacobrxz 您好，TinyBERT只有google drive的下载链接，国内如果不翻墙的话，无法下载google drive上的模型，能否增加一个国内可以直接下载的链接，谢谢~

我翻墙了，怎么也显示：找不到网页
