### ISSUE TITLE
error occured when apply data_augmentation on QNLI  and QQP dataset

### ISSUE THREAD

**Issue by 1024er** [huawei-noah/Pretrained-Language-Model#50]
# tail -f data_augmentation_QNLI.log
![image](https://user-images.githubusercontent.com/17399203/78204142-5f0b9880-74cb-11ea-9e9e-22e71bda9fa1.png)

# tail -f data_augmentation_QQP.log
![image](https://user-images.githubusercontent.com/17399203/78204149-65017980-74cb-11ea-8c6a-edbbf2b3f23c.png)

**Comment by le8888e** [comment]
Hi @1024er, 

I came up with the same problem. Have you fix it? Thank you.

**Comment by DerronXu** [comment]
Hi, Guys,

The same issue.

I guess it might be related to the setting value of 'max_sentence_length'.

Any other idea?

Thanks,
DK

**Comment by XiaoqiJiao** [comment]
Hey, Guys,

try to repalce the func _masked_language_model with the following: 

![image](https://user-images.githubusercontent.com/24711193/96411798-a2d1af80-121b-11eb-9426-b37ae6a32083.png)

**Comment by DerronXu** [comment]
> Hey, Guys, @1024er @le8888e @DerronXu
> 
> try to repalce the func _masked_language_model with the following:
> 
> ![image](https://user-images.githubusercontent.com/24711193/96411798-a2d1af80-121b-11eb-9426-b37ae6a32083.png)

Hi, Xiaoqi,

Thanks!

Your solution works.

Best,
DK
