### ISSUE TITLE
masked_lm_prob default value

### ISSUE THREAD

**Issue by bvnaga** [huawei-noah/Pretrained-Language-Model#59]
In TinyBert/pregrenerate_training_data.py,  masked_lm_prob defaults = 0 (so it masks 1 token).

Trying to understand the default value is 0 was intentional or any recommendations on this?

Just trying to figure out if 1 token masking is enough in the case of TinyBert or depends on the use case.

what was the value used for your experiments?

![image](https://user-images.githubusercontent.com/55558840/79345330-f840a300-7efe-11ea-821f-05d4302a65d2.png)

**Comment by cent-c** [comment]
Yes, it's intensional, because it's the process of distilling, no need for 15% [MASK]. And in version 2 choose no [MASK]. "2nd version (2019/11/18) trained with more (book+wiki) and no [MASK] corpus", After experiments, no [MASK] is better.

**Comment by cent-c** [comment]
Yes, it's intentional, because it's the process of distilling, no need for 15% [MASK]. And in version 2 choose no [MASK]. "2nd version (2019/11/18) trained with more (book+wiki) and no [MASK] corpus", After experiments, no [MASK] is better.
