### ISSUE TITLE
I would like to invite you to test NEZHA or TinyBERT on CLUE Benchmark!

### ISSUE THREAD

**Issue by yechens** [huawei-noah/Pretrained-Language-Model#6]
Hi! Thank you for your great contribution. I am a founder member of CLUE(Language Understanding Evaluation benchmark for Chinese), a group aimed at promoting the development of Chinese language model. 
Recently, we have opened a leaderboard, including 10 different and varied datasets in Chinese. We hope you can use NEZHA or TinyBERT to test these tasks in our platform and promote the development of Chinese language model together  : )
Thank you again!

Our Github: https://github.com/CLUEbenchmark/CLUE 
Leaderboard system: https://www.cluebenchmarks.com/

**Comment by jacobrxz** [comment]
> Hi! Thank you for your great contribution. I am a founder member of CLUE(Language Understanding Evaluation benchmark for Chinese), a group aimed at promoting the development of Chinese language model.
> Recently, we have opened a leaderboard, including 10 different and varied datasets in Chinese. We hope you can use NEZHA or TinyBERT to test these tasks in our platform and promote the development of Chinese language model together : )
> Thank you again!
> 
> Our Github: https://github.com/CLUEbenchmark/CLUE
> Leaderboard system: https://www.cluebenchmarks.com/

我们会考虑您的提议的，谢谢关注~
