### ISSUE TITLE
PD-NER数据集跟NEZHA论文统计的对不上

### ISSUE THREAD

**Issue by GuiminChen** [huawei-noah/Pretrained-Language-Model#62]
你好，可以要下NEZHA论文里的PD-NER数据集吗？根据NEZHA论文里对数据集的统计信息，github里的数据集好像对不上

**Comment by jacobrxz** [comment]
Github里的数据集都是toy数据集，因为版权问题我们不提供数据集，请理解。

已从 Outlook Mobile<https://aka.ms/blhgte> 发送

________________________________
