### ISSUE TITLE
Python 3.x gives "OverflowError"

### ISSUE THREAD

**Issue by akhisreelibra** [huawei-noah/Pretrained-Language-Model#63]
On Windows 10,

Traceback (most recent call last):
  File "task_distill.py", line 43, in <module>
    csv.field_size_limit(sys.maxsize)
OverflowError: Python int too large to convert to C long

**Comment by cent-c** [comment]
hi, you can try it again by removing this line.

**Comment by akhisreelibra** [comment]
Yes. it worked. Thanks. Tried putting a try catch.
