### ISSUE TITLE
TinyBert中文模型什么时候发布大概？

### ISSUE THREAD

**Issue by DeligientSloth** [huawei-noah/Pretrained-Language-Model#64]
1、请问什么时候发布TinyBert中文模型呢？
2、如果没有general distill阶段，直接随机化参数进行task-specific，不知道效果如何（这样的话大概需要什么量级的数据量）？

**Comment by stevewyl** [comment]
同问，只能自己实验了。估计是不会发布了吧

**Comment by SunShuoying** [comment]
同问

**Comment by jacobrxz** [comment]
您好，如果有相关开源计划我们会第一时间告知，多谢关注~
