### ISSUE TITLE
关于数据no mask的问题

### ISSUE THREAD

**Issue by DeligientSloth** [huawei-noah/Pretrained-Language-Model#65]
目前从代码来看， mask_lm_prob是0.0，读代码发现需要mask一个词，后面发布了no mask的模型，是不是说明这个no mask模型训练文本都是没有mask的，一个词也没有mask(我理解中distillation不需要mask的)，如果是这样的话，代码可以简化不少，lm_label_ids, is_next可以省去了（其实这两个在general distillation里面训练的时候也没有用到，不知道为什么要保存这两个fit给模型训练？）

**Comment by cent-c** [comment]
是的，可以省去，蒸馏过程中不需要这两个变量。省去可以简化代码。
