### ISSUE TITLE
论文中Bert_base(Google)和Bert_base(Teacher)分别指什么

### ISSUE THREAD

**Issue by Tiamo666** [huawei-noah/Pretrained-Language-Model#66]
你好，请教一个问题。我在论文中的Table2看见了两个Bert_base,分别是teacher和google。我的理解google就是原始google官网提供的模型，那这个teacher是指什么呢，我在paper中没有找到关于这个的说明，是作者自己pretrain的模型吗？
![截屏2020-06-06 下午3 52 36](https://user-images.githubusercontent.com/41356239/83939218-d6ccab00-a80d-11ea-9a29-c8faa069fa0f.png)

**Comment by cent-c** [comment]
google 是 bert论文里report的结果；teacher用的还是google的bert，只不过是自己fine-tune之后得到的结果；这两行的GLUE数据对比主要为了保证自己的fine-tune是没有问题的，即和google论文中report的结果是基本一致的。

**Comment by Tiamo666** [comment]
哦，非常感谢，我明白了！
