### ISSUE TITLE
Incremental pretraining to supplement PositionEmbedding？

### ISSUE THREAD

**Issue by P01son6415** [huawei-noah/Pretrained-Language-Model#69]
为了使用BERT框架加载Nezha模型，我们想通过增量预训练补充Position Embedding部分权重，请问这样是可行的吗？目前的实验发现收敛的速度很慢，似乎相当于从头预训练了。

**Comment by ItachiUchihaVictor** [comment]
> 为了使用BERT框架加载Nezha模型，我们想通过增量预训练补充Position Embedding部分权重，请问这样是可行的吗？目前的实验发现收敛的速度很慢，似乎相当于从头预训练了。

没这样试过 但感觉不太合理 毕竟NEZHA和BERT是不同的架构 用NEZHA初始化BERT可能会有副作用
