### ISSUE TITLE
Chinese TinyBERT

### ISSUE THREAD

**Issue by luzm3** [huawei-noah/Pretrained-Language-Model#7]
现在公开的bert是英文版的么，中文版的啥时候发布呀

**Comment by nlpBeginner** [comment]
> 现在公开的bert是英文版的么，中文版的啥时候发布呀

现在公开的TinyBERT是英文版的。中文版的正在训练和测试中，会尽快发布的。

**Comment by 1024er** [comment]
强烈建议尽快放出来中文地😁

**Comment by zshy1205** [comment]
> 强烈建议尽快放出来中文地

强烈希望中文版tinybert放出来，然后测试在中文上的真实效果。
