### ISSUE TITLE
how to set the config file of student_model?

### ISSUE THREAD

**Issue by jinsongpan** [huawei-noah/Pretrained-Language-Model#70]
when I intend to train the general chinese tinybert model, I meet some problems that  the project doesn't offer the example of the config file, so could anyone offer me a reference of the config file of student_model. 
![image](https://user-images.githubusercontent.com/33392010/86701287-7915c380-c044-11ea-9de9-2b419f7bb5a6.png)
thanks for your kindness!

**Comment by cent-c** [comment]
Hi, You need to change the value of the "vocab_size" parameter in the config file of TinyBert to 21128, which is the same as the value of this parameter in the Nezha model.

**Comment by jinsongpan** [comment]
Thanks for your reply. I set yhe config file as the netfriend mentioned in https://github.com/huawei-noah/Pretrained-Language-Model/issues/24#issuecomment-573483671.
What's more, I have another question about the file of  "${FT_BERT_BASE_DIR}". why the part need a fine-tuned BERT_BASE? And how to generate  it ?(e.g. if I want to test QQP task, I need fine-tuning the bert model on the QQP dataset before I start task distillation?)

**Comment by cent-c** [comment]
Yes, you need a finetuned Bert-base to ensure that the teacher model is already performing well in this task. For details about the way to generate it, you can see the open source implementation of huggingface : https://github.com/huggingface/transformers

**Comment by jinsongpan** [comment]
> Yes, you need a finetuned Bert-base to ensure that the teacher model is already performing well in this task. For details about the way to generate it, you can see the open source implementation of huggingface : https://github.com/huggingface/transformers

got it. thx!
