### ISSUE TITLE
数据是否存在问题

### ISSUE THREAD

**Issue by DC-Lin** [huawei-noah/Pretrained-Language-Model#71]
复现预训练过程，出现问题
learning_rate=3e-8
batch_size=16
![image](https://user-images.githubusercontent.com/38984443/86766511-3c19f300-c07d-11ea-8180-f9dc535a3133.png)

**Comment by jacobrxz** [comment]
数据还是自己处理一下，这里之前的只是做一个示例，另外你的lr设置的太小了，谢谢关注。
