### ISSUE TITLE
how to set StopWordsList of chinese in data_augmentation.py?

### ISSUE THREAD

**Issue by jinsongpan** [huawei-noah/Pretrained-Language-Model#73]
As the title.

**Comment by SunShuoying** [comment]
@jinsongpan hi, how to get chinese glove embedding?

**Comment by jinsongpan** [comment]
I just download the cn-wiki-embedding from the internet.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "huawei-noah/Pretrained-Language-Model"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月26日(星期三) 中午11:36
收件人:&nbsp;"huawei-noah/Pretrained-Language-Model"<Pretrained-Language-Model@noreply.github.com&gt;;
抄送:&nbsp;"Sunnyrain"<761086340@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [huawei-noah/Pretrained-Language-Model] how to set StopWordsList of chinese in data_augmentation.py? (#73)





 
@jinsongpan hi, how to get chinese glove embedding?
