### ISSUE TITLE
About cost of general distillation in tinyBERT

### ISSUE THREAD

**Issue by wanghaoshuang** [huawei-noah/Pretrained-Language-Model#75]
>For the general distillation, we use English Wikipedia (2,500 M words) as the text corpus and perform the intermediate layer distillation for 3 epochs with the supervision from a pre-trained BERTBASE teacher and keep other hyper-parameters same as BERT pre-training 

请问，使用general_distill.py训练上述过程，大概的耗时和计算资源是多少？

**Comment by cent-c** [comment]
Hi, GD的计算消耗根据实验结果在蒸馏4层模型时大约为2240 V100 GPU hours，蒸馏6层模型时大约为2880 V100 GPU hours。 这是在使用data_parallel时的耗时。而如果使用horovod并行方法，速度会快2倍以上。
