### ISSUE TITLE
num_train_epochs in task_distill.py

### ISSUE THREAD

**Issue by llyx97** [huawei-noah/Pretrained-Language-Model#77]
line 816 of task_distill.py is: 
    args.num_train_epoch = default_params[task_name]["num_train_epochs"]
I think it should be: 
    args.num_train_epochs = default_params[task_name]["num_train_epochs"]
otherwise the num_train_epochs in default_params will be invalid.

**Comment by cent-c** [comment]
Hi, this is indeed a mistake, and we will correct it. Thank you!
