### ISSUE TITLE
预训练模型下载链接不存在

### ISSUE THREAD

**Issue by 787264137** [huawei-noah/Pretrained-Language-Model#8]
你好，下载链接不存在，麻烦重新发下

**Comment by nlpBeginner** [comment]
> 你好，下载链接不存在，麻烦重新发下

是哪个链接不存在？

**Comment by jacobrxz** [comment]
> 你好，下载链接不存在，麻烦重新发下

NEZHA模型链接正在更新

**Comment by 787264137** [comment]
> > 你好，下载链接不存在，麻烦重新发下
> 
> 是哪个链接不存在？
Models download, password: x3qk 
是这个download字符串对应的链接

**Comment by nlpBeginner** [comment]
> > > 你好，下载链接不存在，麻烦重新发下
> > 
> > 
> > 是哪个链接不存在？
> > Models download, password: x3qk
> > 是这个download字符串对应的链接

NEZHA模型链接正在更新

**Comment by jacobrxz** [comment]
> 你好，下载链接不存在，麻烦重新发下

已经更新~
