### ISSUE TITLE
中文general distillation 效果不佳

### ISSUE THREAD

**Issue by vincentlux** [huawei-noah/Pretrained-Language-Model#84]
非常感谢可以开源这个项目！我试了下用 zh-wiki ～3000万句话的语料去做general distillation，attention loss 和rep loss都正常下降，并在训练2个epoch后稳定在4.5; 1.2左右。然而获得的模型看起来并没有学到什么知识，试了MLM 这个task的效果如下：

请问[MASK]有披萨店？
[MASK] 0: 羧

[MASK] 0: こ

[MASK] 0: 變

[MASK] 0: 熱

[MASK] 0: 热

披萨好吃，我想吃[MASK]。
[MASK] 0: こ

[MASK] 0: 變

[MASK] 0: 热

[MASK] 0: 熱

[MASK] 0: 变

中国位于[MASK]洲大陆
[MASK] 0: 莽

[MASK] 0: 旱

[MASK] 0: 流

[MASK] 0: 漓

[MASK] 0: 证

请问是哪里搞错了吗，还是general distillation的模型确实在MLM任务上表现不佳？ 谢谢！

**Comment by yzq170320** [comment]
您好，我也遇到类似的问题，请问有什么技巧可言提高效果？
