### ISSUE TITLE
bert 在Finetune 好之后作为teacher和student模型进行拟合。请问student模型哪里来？

### ISSUE THREAD

**Issue by charlesfufu** [huawei-noah/Pretrained-Language-Model#87]
bert 在Finetune 好之后作为teacher和student模型进行拟合。请问student模型哪里来？

**Comment by cent-c** [comment]
ReadMe中公开了student模型：
General_TinyBERT_v2(4layer-312dim)
General_TinyBERT_v2(6layer-768dim)

**Comment by charlesfufu** [comment]
> ReadMe中公开了student模型：
> General_TinyBERT_v2(4layer-312dim)
> General_TinyBERT_v2(6layer-768dim)

这些不是蒸馏好了的模型用于评估的吗？另外我要是其它自己的任务可以在这些模型基础上当成初始值去进行蒸馏吗。

**Comment by cent-c** [comment]
这些是GD蒸馏后的TinyBert模型，还需要在具体任务上进行任务相关的TD才可以用于评估，TD后的小模型在README中也都公开了。所以如果是其它的任务，是可以利用它进行TD的。

**Comment by charlesfufu** [comment]
> 这些是GD蒸馏后的TinyBert模型，还需要在具体任务上进行任务相关的TD才可以用于评估，TD后的小模型在README中也都公开了。所以如果是其它的任务，是可以利用它进行TD的。

对的，我想问的是在相关任务做td的时候student的初始模型是用什么？

**Comment by cent-c** [comment]
是GD后的TinyBert模型。即General_TinyBERT_v2。细节上可以看 TinyBERT: Distilling BERT for Natural Language Understanding.

**Comment by charlesfufu** [comment]
> 是GD后的TinyBert模型。即General_TinyBERT_v2。细节上可以看 TinyBERT: Distilling BERT for Natural Language Understanding.

那请问在TD任务中的teacher 的模型是什么模型。我看过相关的paper但是感觉解释的不是很清楚

**Comment by cent-c** [comment]
teacher模型是fine-tuned BERT，即需要将Bert在某任务上finetune，之后它可以作为teacher在该任务上对小模型进行TD蒸馏。

**Comment by charlesfufu** [comment]
> teacher模型是fine-tuned BERT，即需要将Bert在某任务上finetune，之后它可以作为teacher在该任务上对小模型进行TD蒸馏。

多谢回复
