### ISSUE TITLE
Where can I find the learnable linear transformation W_h in TinyBERT？

### ISSUE THREAD

**Issue by guoqunabc** [huawei-noah/Pretrained-Language-Model#9]
There is a  learnable linear transformation W_h (Equation 8) in the TinyBERT paper, could you plz tell me where can I find the code implementation for the transformation? Thanks for you early response.

![1](https://user-images.githubusercontent.com/9532020/70422192-4bfd3480-1aa6-11ea-80d6-af76a3d1079d.png)
![3](https://user-images.githubusercontent.com/9532020/70422743-2cb2d700-1aa7-11ea-9334-f88020e4878a.png)

**Comment by nlpBeginner** [comment]
> There is a learnable linear transformation W_h (Equation 8) in the TinyBERT paper, could you plz tell me where can I find the code implementation for the transformation? Thanks for you early response.
> 
> ![1](https://user-images.githubusercontent.com/9532020/70422192-4bfd3480-1aa6-11ea-80d6-af76a3d1079d.png)
> ![3](https://user-images.githubusercontent.com/9532020/70422743-2cb2d700-1aa7-11ea-9334-f88020e4878a.png)

in transformer.modeling.py file.
![image](https://user-images.githubusercontent.com/34981073/70424337-2c680b00-1aaa-11ea-95db-36484850438c.png)

**Comment by guoqunabc** [comment]
Very helpful, thank you very much
