### ISSUE TITLE
wwm model 分词工具

### ISSUE THREAD

**Issue by xv44586** [huawei-noah/Pretrained-Language-Model#96]
中文wwm model 是使用的哪种分词工具处理的数据？

**Comment by ItachiUchihaVictor** [comment]
> 中文wwm model 是使用的哪种分词工具处理的数据？

和中文非wwm的模型是一样的 具体见Pretrained-Language-Model/NEZHA-TensorFlow/tokenization.py

**Comment by xv44586** [comment]
tokenization 是做tokenize的吧？我的意思是做全词mask 时，如何segment 确定词的边界？我在create_pretrain_data.py 中的代码只有random mask的，所以我想问一下在处理全词mask 时的分词工具是什么？jieba？ltp？还是自研的

**Comment by ItachiUchihaVictor** [comment]
> tokenization 是做tokenize的吧？我的意思是做全词mask 时，如何segment 确定词的边界？我在create_pretrain_data.py 中的代码只有random mask的，所以我想问一下在处理全词mask 时的分词工具是什么？jieba？ltp？还是自研的

我们当时是把jieba分词融入了这个tokenization.py 用以确定词的边界 这个改起来应该不难 我们后面也会考虑公布这个WWM的tokenization.py

**Comment by xv44586** [comment]
嗯，谢谢，因为我用你们的wwm模型继续预训练时使用的是jieba，所以为了和你们保持一致，来确认一下。再次感谢开源模型！
